DROP DATABASE IF EXISTS ice_dude;
CREATE DATABASE ice_dude;
USE ice_dude;

CREATE TABLE Users (
    UserID INT PRIMARY KEY AUTO_INCREMENT,
    UserLevel INT CHECK (UserLevel IN (1,2)) NOT NULL,
    Username VARCHAR(255) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL UNIQUE,
    Phone INT NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IceCream (
    IceCreamID INT PRIMARY KEY AUTO_INCREMENT,
    IceCreamName VARCHAR(255) NOT NULL,
    IceCreamDescription VARCHAR(255) NOT NULL,
    IceCreamPrice DECIMAL(8, 2) NOT NULL,
    IceCreamImage VARCHAR(255), -- URL path to image
);

CREATE TABLE Orders (
    OrderID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    UserID INT,
    OrderDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
);

CREATE TABLE Cart (
    CartID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    OrderID INT NOT NULL,
    IceCreamID INT NOT NULL,
    FOREIGN KEY (OrderID) REFERENCES Orders(OrderID)
);

CREATE TABLE IceCream_Quantity (
    IceCream_Quantity_ID INT PRIMARY KEY AUTO_INCREMENT,
    IceCreamID INT NOT NULL,
    CartID INT NOT NULL,
    Quantity INT NOT NULL,
    CONSTRAINT positive_quantity CHECK (Quantity > 0),
    FOREIGN KEY (IceCreamID) REFERENCES IceCream(IceCreamID),
    FOREIGN KEY (CartID) REFERENCES Cart(CartID)
);